feat(gtk-threadsafe): add support for kwargs
Using `functools.partial` is a convenient way to add support for keyword
arguments to callback functions where keyword arguments are not directly
supported by the calling library.  With respect to this library,
`functools.partial()` could be used to add keyword arguments support to
the `gtk_threadsafe()` decorator, since the decorator uses
`gobject.idle_add()` (which does not accept keyword arguments) to schedule
execution in the main GTK thread.

Unfortunately, prior to this commit, applying the `gtk_threadsafe`
decorator to a function wrapped with `functools.partial()` causes an
exception, e.g.:

```python
In [6]: pygtkhelpers.gthreads.gtk_threadsafe(ft.partial(foo, bar='hello, world'))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-a0ff0095e599> in <module>()
----> 1 pygtkhelpers.gthreads.gtk_threadsafe(ft.partial(foo, bar='hello, world'))

C:\Users\chris\Miniconda2-x86\envs\db-dev-copy\lib\site-packages\pygtkhelpers\gthreads.py in gtk_threadsafe(func)
    242     gtk.gdk.threads_init()
    243
--> 244     @functools.wraps(func)
    245     def _gtk_threadsafe(*args):
    246         gobject.idle_add(func, *args)

C:\Users\chris\Miniconda2-x86\envs\db-dev-copy\lib\functools.pyc in update_wrapper(wrapper, wrapped, assigned, updated)
     31     """
     32     for attr in assigned:
---> 33         setattr(wrapper, attr, getattr(wrapped, attr))
     34     for attr in updated:
     35         getattr(wrapper, attr).update(getattr(wrapped, attr, {}))

AttributeError: 'functools.partial' object has no attribute '__module__'
```

In this commit, update `gtk_threadsafe()` to accept functions wrapped with
`functools.partial()`.  Also, ignore the return value of functions wrapped
with `gtk_threadsafe()` to prevent the callback from being called
repeatedly indefinitely.  From the [`gobject.idle_add()`
documentation][1]:

> If callback returns FALSE it is automatically removed from the list of
> event sources and will not be called again.

[1]: http://library.isr.ist.utl.pt/docs/pygtk2reference/gobject-functions.html#function-gobject--idle-add